# @package _global_

# ! Dataset Preprocessing
preprocess_device: cpu # Set to cpu if your GPU memory is below 32GB
add_self_loop: false
to_bidirected: true

# ! Train and Evaluation Dataset Lookup
dataset: Debug
train_datasets: ${oc.select:_dataset_lookup.${dataset}.train,${dataset}}
eval_datasets: ${oc.select:_dataset_lookup.${dataset}.eval,${dataset}}
_trans_datasets: [ Arxiv, Product, Cora, Wisconsin ] # Used when identifying heldout datasets.

range_eval_datasets: [
  Cora,
  FCora,
  Citeseer,
  DBLP,
  Pubmed,
  Wiki,
  WkCS,
  AmzComp,
  AmzPhoto,
  BlogCatalog,
  CoCS,
  CoPhysics,
  Cornell,
  Texas,
  Wisconsin,
  AirBrazil,
  AirUS,
  AirEU,
  Chameleon,
  Actor,
  Squirrel,
  Roman,
  AmzRatings,
  Minesweeper,
  Tolokers,
  Questions,
]

_all_datasets: [
  Arxiv,
  Cora,
  FCora,
  Citeseer,
  DBLP,
  Pubmed,
  Wiki,
  WkCS,
  Reddit,

  Product,
  AmzComp,
  AmzPhoto,
  BlogCatalog,
  LastFMAsia,
  Deezer,

  CoCS,
  CoPhysics,
  Cornell,
  Texas,
  Wisconsin,
  AirBrazil,
  AirUS,
  AirEU,

  Chameleon,
  Actor,
  Squirrel,
  Roman,
  AmzRatings,
  Minesweeper,
  Tolokers,
  Questions,
]

all_and_hopsign_datasets_demo:
  [
    2HopSign,
    5HopSign,
    8HopSign,
    Cora,
    Citeseer,
    DBLP,
    AirUS,
    AirEU,
    AirBrazil,
  ] # smaller set for demo purposes

all_and_hopsign_datasets:
  [
    1HopSign,
    2HopSign,
    3HopSign,
    4HopSign,
    5HopSign,
    6HopSign,
    7HopSign,
    8HopSign,
    Cora,
    FCora,
    Citeseer,
    DBLP,
    Pubmed,
    Wiki,
    WkCS,
    AmzComp,
    AmzPhoto,
    BlogCatalog,
    CoCS,
    CoPhysics,
    Cornell,
    Texas,
    Wisconsin,
    AirBrazil,
    AirUS,
    AirEU,
    Chameleon,
    Actor,
    Squirrel,
    Roman,
    AmzRatings,
    Minesweeper,
    Tolokers,
    Questions,
  ]

_dataset_lookup:
  Debug:
    train: [ Wisconsin ]
    eval: [ Texas ]
  CoraXAll:
    train: [ Cora ]
    eval: ${_all_datasets}
  WisXAll:
    train: [ Wisconsin ]
    eval: ${_all_datasets}
  ArxivXAll:
    train: [ Arxiv ]
    eval: ${_all_datasets}
  ProdXAll:
    train: [ Product ]
    eval: ${_all_datasets}


  WisconsinXAllAndHopSign:
    train: [ Wisconsin ]
    eval: ${all_and_hopsign_datasets}

  WisconsinXAllAndHopSignDemo:
    train: [ Wisconsin ]
    eval: ${all_and_hopsign_datasets_demo}


  # All train-eval pairs; likely inefficient but it works for now
  # ! Train × Eval grid (full)
  WisconsinXAirBrazil:
    train: [ Wisconsin ]
    eval: AirBrazil
  WisconsinXCornell:
    train: [ Wisconsin ]
    eval: Cornell
  WisconsinXTexas:
    train: [ Wisconsin ]
    eval: Texas
  WisconsinXWisconsin:
    train: [ Wisconsin ]
    eval: Wisconsin
  WisconsinXAirEU:
    train: [ Wisconsin ]
    eval: AirEU
  WisconsinXAirUS:
    train: [ Wisconsin ]
    eval: AirUS
  WisconsinXSquirrel:
    train: [ Wisconsin ]
    eval: Squirrel
  WisconsinXWiki:
    train: [ Wisconsin ]
    eval: Wiki
  WisconsinXCora:
    train: [ Wisconsin ]
    eval: Cora
  WisconsinXCiteseer:
    train: [ Wisconsin ]
    eval: Citeseer
  WisconsinXBlogCatalog:
    train: [ Wisconsin ]
    eval: BlogCatalog
  WisconsinXChameleon:
    train: [ Wisconsin ]
    eval: Chameleon
  WisconsinXActor:
    train: [ Wisconsin ]
    eval: Actor
  WisconsinXLastFMAsia:
    train: [ Wisconsin ]
    eval: LastFMAsia
  WisconsinXAmzPhoto:
    train: [ Wisconsin ]
    eval: AmzPhoto
  WisconsinXMinesweeper:
    train: [ Wisconsin ]
    eval: Minesweeper
  WisconsinXWkCS:
    train: [ Wisconsin ]
    eval: WkCS
  WisconsinXTolokers:
    train: [ Wisconsin ]
    eval: Tolokers
  WisconsinXAmzComp:
    train: [ Wisconsin ]
    eval: AmzComp
  WisconsinXDBLP:
    train: [ Wisconsin ]
    eval: DBLP
  WisconsinXCoCS:
    train: [ Wisconsin ]
    eval: CoCS
  WisconsinXPubmed:
    train: [ Wisconsin ]
    eval: Pubmed
  WisconsinXFCora:
    train: [ Wisconsin ]
    eval: FCora
  WisconsinXRoman:
    train: [ Wisconsin ]
    eval: Roman
  WisconsinXAmzRatings:
    train: [ Wisconsin ]
    eval: AmzRatings
  WisconsinXDeezer:
    train: [ Wisconsin ]
    eval: Deezer
  WisconsinXCoPhysics:
    train: [ Wisconsin ]
    eval: CoPhysics
  WisconsinXQuestions:
    train: [ Wisconsin ]
    eval: Questions
  WisconsinXArxiv:
    train: [ Wisconsin ]
    eval: Arxiv
  WisconsinXReddit:
    train: [ Wisconsin ]
    eval: Reddit
  WisconsinXProduct:
    train: [ Wisconsin ]
    eval: Product

  CoraXAirBrazil:
    train: [ Cora ]
    eval: AirBrazil
  CoraXCornell:
    train: [ Cora ]
    eval: Cornell
  CoraXTexas:
    train: [ Cora ]
    eval: Texas
  CoraXWisconsin:
    train: [ Cora ]
    eval: Wisconsin
  CoraXAirEU:
    train: [ Cora ]
    eval: AirEU
  CoraXAirUS:
    train: [ Cora ]
    eval: AirUS
  CoraXSquirrel:
    train: [ Cora ]
    eval: Squirrel
  CoraXWiki:
    train: [ Cora ]
    eval: Wiki
  CoraXCora:
    train: [ Cora ]
    eval: Cora
  CoraXCiteseer:
    train: [ Cora ]
    eval: Citeseer
  CoraXBlogCatalog:
    train: [ Cora ]
    eval: BlogCatalog
  CoraXChameleon:
    train: [ Cora ]
    eval: Chameleon
  CoraXActor:
    train: [ Cora ]
    eval: Actor
  CoraXLastFMAsia:
    train: [ Cora ]
    eval: LastFMAsia
  CoraXAmzPhoto:
    train: [ Cora ]
    eval: AmzPhoto
  CoraXMinesweeper:
    train: [ Cora ]
    eval: Minesweeper
  CoraXWkCS:
    train: [ Cora ]
    eval: WkCS
  CoraXTolokers:
    train: [ Cora ]
    eval: Tolokers
  CoraXAmzComp:
    train: [ Cora ]
    eval: AmzComp
  CoraXDBLP:
    train: [ Cora ]
    eval: DBLP
  CoraXCoCS:
    train: [ Cora ]
    eval: CoCS
  CoraXPubmed:
    train: [ Cora ]
    eval: Pubmed
  CoraXFCora:
    train: [ Cora ]
    eval: FCora
  CoraXRoman:
    train: [ Cora ]
    eval: Roman
  CoraXAmzRatings:
    train: [ Cora ]
    eval: AmzRatings
  CoraXDeezer:
    train: [ Cora ]
    eval: Deezer
  CoraXCoPhysics:
    train: [ Cora ]
    eval: CoPhysics
  CoraXQuestions:
    train: [ Cora ]
    eval: Questions
  CoraXArxiv:
    train: [ Cora ]
    eval: Arxiv
  CoraXReddit:
    train: [ Cora ]
    eval: Reddit
  CoraXProduct:
    train: [ Cora ]
    eval: Product

  ArxivXAirBrazil:
    train: [ Arxiv ]
    eval: AirBrazil
  ArxivXCornell:
    train: [ Arxiv ]
    eval: Cornell
  ArxivXTexas:
    train: [ Arxiv ]
    eval: Texas
  ArxivXWisconsin:
    train: [ Arxiv ]
    eval: Wisconsin
  ArxivXAirEU:
    train: [ Arxiv ]
    eval: AirEU
  ArxivXAirUS:
    train: [ Arxiv ]
    eval: AirUS
  ArxivXSquirrel:
    train: [ Arxiv ]
    eval: Squirrel
  ArxivXWiki:
    train: [ Arxiv ]
    eval: Wiki
  ArxivXCora:
    train: [ Arxiv ]
    eval: Cora
  ArxivXCiteseer:
    train: [ Arxiv ]
    eval: Citeseer
  ArxivXBlogCatalog:
    train: [ Arxiv ]
    eval: BlogCatalog
  ArxivXChameleon:
    train: [ Arxiv ]
    eval: Chameleon
  ArxivXActor:
    train: [ Arxiv ]
    eval: Actor
  ArxivXLastFMAsia:
    train: [ Arxiv ]
    eval: LastFMAsia
  ArxivXAmzPhoto:
    train: [ Arxiv ]
    eval: AmzPhoto
  ArxivXMinesweeper:
    train: [ Arxiv ]
    eval: Minesweeper
  ArxivXWkCS:
    train: [ Arxiv ]
    eval: WkCS
  ArxivXTolokers:
    train: [ Arxiv ]
    eval: Tolokers
  ArxivXAmzComp:
    train: [ Arxiv ]
    eval: AmzComp
  ArxivXDBLP:
    train: [ Arxiv ]
    eval: DBLP
  ArxivXCoCS:
    train: [ Arxiv ]
    eval: CoCS
  ArxivXPubmed:
    train: [ Arxiv ]
    eval: Pubmed
  ArxivXFCora:
    train: [ Arxiv ]
    eval: FCora
  ArxivXRoman:
    train: [ Arxiv ]
    eval: Roman
  ArxivXAmzRatings:
    train: [ Arxiv ]
    eval: AmzRatings
  ArxivXDeezer:
    train: [ Arxiv ]
    eval: Deezer
  ArxivXCoPhysics:
    train: [ Arxiv ]
    eval: CoPhysics
  ArxivXQuestions:
    train: [ Arxiv ]
    eval: Questions
  ArxivXArxiv:
    train: [ Arxiv ]
    eval: Arxiv
  ArxivXReddit:
    train: [ Arxiv ]
    eval: Reddit
  ArxivXProduct:
    train: [ Arxiv ]
    eval: Product

  ProductXAirBrazil:
    train: [ Product ]
    eval: AirBrazil
  ProductXCornell:
    train: [ Product ]
    eval: Cornell
  ProductXTexas:
    train: [ Product ]
    eval: Texas
  ProductXWisconsin:
    train: [ Product ]
    eval: Wisconsin
  ProductXAirEU:
    train: [ Product ]
    eval: AirEU
  ProductXAirUS:
    train: [ Product ]
    eval: AirUS
  ProductXSquirrel:
    train: [ Product ]
    eval: Squirrel
  ProductXWiki:
    train: [ Product ]
    eval: Wiki
  ProductXCora:
    train: [ Product ]
    eval: Cora
  ProductXCiteseer:
    train: [ Product ]
    eval: Citeseer
  ProductXBlogCatalog:
    train: [ Product ]
    eval: BlogCatalog
  ProductXChameleon:
    train: [ Product ]
    eval: Chameleon
  ProductXActor:
    train: [ Product ]
    eval: Actor
  ProductXLastFMAsia:
    train: [ Product ]
    eval: LastFMAsia
  ProductXAmzPhoto:
    train: [ Product ]
    eval: AmzPhoto
  ProductXMinesweeper:
    train: [ Product ]
    eval: Minesweeper
  ProductXWkCS:
    train: [ Product ]
    eval: WkCS
  ProductXTolokers:
    train: [ Product ]
    eval: Tolokers
  ProductXAmzComp:
    train: [ Product ]
    eval: AmzComp
  ProductXDBLP:
    train: [ Product ]
    eval: DBLP
  ProductXCoCS:
    train: [ Product ]
    eval: CoCS
  ProductXPubmed:
    train: [ Product ]
    eval: Pubmed
  ProductXFCora:
    train: [ Product ]
    eval: FCora
  ProductXRoman:
    train: [ Product ]
    eval: Roman
  ProductXAmzRatings:
    train: [ Product ]
    eval: AmzRatings
  ProductXDeezer:
    train: [ Product ]
    eval: Deezer
  ProductXCoPhysics:
    train: [ Product ]
    eval: CoPhysics
  ProductXQuestions:
    train: [ Product ]
    eval: Questions
  ProductXArxiv:
    train: [ Product ]
    eval: Arxiv
  ProductXReddit:
    train: [ Product ]
    eval: Reddit
  ProductXProduct:
    train: [ Product ]
    eval: Product

  # Train on Arxiv, inference on Cora and Citeseer
  CoraCiteInference:
    train: [ Arxiv ]
    eval: [ Cora, Citeseer ]

# ! Dataset Meta Data
_ds_meta_data:
  # Format: Tuple of 3 (Interface, Alias: ${collection}.${name} if PYG else dgl_target_name)
  # Comments: Nodes, Edges, Features, Classes
  # ! Document Topic Classification: Nodes are documents, edges are references/citations/written-by-same-author, goal is to classify the topic of document
  Arxiv: ogb, ogbn-arxiv # 168,343 1,166,243 100 40
  Cora: pyg, Planetoid.Cora # 2,708 10,556 1,433 7
  FCora: pyg, CitationFull.Cora # 19,793 126,842 8,710 70
  Citeseer: pyg, Planetoid.CiteSeer # 3,327 9,104 3,703 6
  DBLP: pyg, CitationFull.DBLP # 17,716 105,734 1,639 4
  Pubmed: pyg, Planetoid.PubMed # 19,717 88,648 500 3
  Wiki: pyg, AttributedGraphDataset.Wiki # 2,405 17,981 4,973 17
  WkCS: pyg, WikiCS # 11,701, 431,726 300 10
  # nodes (posts) are connected if they are posted by same user, labels are "subreddit"
  Reddit: pyg, Reddit # 232,965 114,615,892 602 41

  # ! Author Field Classification: Nodes are authors, edges are co-author,  goal is to classify author topic
  CoCS: pyg, Coauthor.CS # 18,333 163,788 6,805 15
  CoPhysics: pyg, Coauthor.Physics # 34,493 495,924 8,415 5

  # ! WebKB: nodes represent web pages, and edges are hyperlinks between them. Node features are the bag-of-words representation of web pages. The web pages are manually classified into the five categories, student, project, course, staff, and faculty.
  Cornell: dgl, CornellDataset # 183 298 1,703 5
  # ! Use the data preprocessed by (https://arxiv.org/abs/2302.11640) to avoid label issues.
  Texas: heterophilous, texas_4_classes # 183 325 1,703 4
  Wisconsin: dgl, WisconsinDataset # 251 515 1,703 5

  # ! Traffic prediction
  # WikiTraffic: Nodes represent web pages and edges represent hyperlinks between them. Node features represent several informative nouns in the Wikipedia pages. The task is to predict the average daily traffic of the web page.
  Chameleon: pyg, WikipediaNetwork.chameleon # 5201, 217073, 2089, 5
  Squirrel: pyg, WikipediaNetwork.squirrel # 2277, 36101, 2325, 5
  # Airport traffic graphs
  AirBrazil: pyg, Airports.Brazil # 131 1,038 131 4
  AirUS: pyg, Airports.USA # 1,190 13,599 1190 4
  AirEU: pyg, Airports.Europe # 399 5,995 399 4

  # ! HeterophilousGraphDataset
  # See https://arxiv.org/abs/2302.11640 for details
  Roman: pyg, HeterophilousGraphDataset.Roman-empire # 22,662 32,927 300 18
  AmzRatings: pyg, HeterophilousGraphDataset.Amazon-ratings # 24,492 93,050 300 5
  Minesweeper: pyg, HeterophilousGraphDataset.Minesweeper # 10,000 39,402 7 2
  Tolokers: pyg, HeterophilousGraphDataset.Tolokers # 11,758 519,000 10 2
  Questions: pyg, HeterophilousGraphDataset.Questions # 48,921 153,540 301 2

  # Each node corresponds to an actor, and the edge between two nodes denotes co-occurrence on the same Wikipedia page. Node features correspond to some keywords in the Wikipedia pages. The task is to classify the nodes into five categories in terms of words of actor’s Wikipedia.
  Actor: pyg, Actor # 7,600 30,019 932 5


  # ! Ecommerce
  AmzComp: pyg, Amazon.Computers # 13,752 491,722 767 10
  AmzPhoto: pyg, Amazon.Photo # 7,650 238,162 745 8
  Product: ogb, ogbn-products # 2,449,029 61,859,140 100 47

  # ! Social Network Communities: Community detection in social networks with user description as features.
  BlogCatalog: pyg, AttributedGraphDataset.BlogCatalog # 5,196 343,486 8,189 6
  LastFMAsia: pyg, LastFMAsia # 7,624, 55,612, 128, 18
  # A social network of European Deezer users
  #which we collected from the public API in March 2020. Nodes
  #represent users and links are mutual follower relationships
  #among users. The related classification task is the prediction
  #of gender using the friendship graph and the artists liked.
  Deezer: pyg, DeezerEurope # 28,281, 185,504, 128, 2

  # Range-related
  1HopSign: k_hop_sign, SyntheticDataset.1HopSign
  2HopSign: k_hop_sign, SyntheticDataset.2HopSign
  3HopSign: k_hop_sign, SyntheticDataset.3HopSign
  4HopSign: k_hop_sign, SyntheticDataset.4HopSign 
  5HopSign: k_hop_sign, SyntheticDataset.5HopSign
  6HopSign: k_hop_sign, SyntheticDataset.6HopSign
  7HopSign: k_hop_sign, SyntheticDataset.7HopSign
  8HopSign: k_hop_sign, SyntheticDataset.8HopSign